language: python

python:
  - "3.5"

services:
  - postgresql

install:
  - pip install -r requirements/test-requirements.txt

before_script:
  - cp ecom_merci/.env_test ecom_merci/.env
  - ./check_migrations.sh
  - flake8 --exclude='ipython_log.py*,migrations,templates, manage.py' .
  - psql -c "CREATE USER ecom_merci_test WITH PASSWORD 'ecom_merci_test'" -U postgres;
  - psql -c "CREATE DATABASE ecom_merci_test OWNER ecom_merci_test;" -U postgres

script:
  - ./manage.py migrate
  - py.test --create-db

addons:
    hosts:
        - 127.0.0.1 ecom_mercidb
